FROM python:2

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# you'll want to override this to set your own args, probably
CMD [ "python", "./loaddb.py" ]
