# Same version as CDO
FROM python:3.4

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# You'll probably want to override this to set your own args
CMD [ "python", "./loaddb.py" ]
