#!/bin/bash

DIR=/home/crawl/chroot/var/games/crawl07/saves

ln -s $DIR/logfile cao-logfile-0.7
ln -s $DIR/logfile-sprint cao-logfile-0.7-sprint
ln -s $DIR/milestones cao-milestones-0.7
ln -s $DIR/milestones-sprint cao-milestones-0.7-sprint
