UNIQUES = ["Agnes", "Aizul", "Amaemon", "Antaeus", "Arachne", "Asmodeus",
           "Asterion", "Azrael", "Bai Suzhen", "Blorkula the Orcula", "Boris",
           "Cerebov", "Crazy Yiuf", "Dispater", "Dissolution", "Donald",
           "Dowan", "Duvessa", "Edmund", "the Enchantress", "Ereshkigal",
           "Erica", "Erolcha", "Eustachio", "Fannar", "Frances", "Frederick",
           "Gastronok", "Geryon", "Gloorx Vloq", "Grinder", "Grum", "Grunn",
           "Harold", "Ignacio", "Ijyb", "Ilsuiw", "Jeremiah", "Jessica",
           "Jorgrun", "Jory", "Joseph", "Josephine", "Josephina", "Khufu",
           "Kirke", "the Lernaean hydra", "Lodul", "Lom Lobon", "Louise",
           "Maggie", "Mara", "Margery", "Maurice", "Menkaure", "Mennas",
           "Mlioglotl", "Mnoleg", "Murray", "Natasha", "Nergalle", "Nessos",
           "Nikola", "Nobody", "Norris", "Parghit", "Pargi", "Pikel",
           "Polyphemus", "Prince Ribbit", "Psyche", "Robin", "Roxanne",
           "the Royal Jelly", "Rupert", "Saint Roka", "the Serpent of Hell",
           "Sigmund", "Snorg", "Sojobo", "Sonja", "Sprozz", "Terence",
           "Tiamat", "Urug", "Vashnia", "Vv", "Wiglaf", "Xak'krixis", "Xtahua",
           "Zenata"]
UNIQUES.sort()
